---
- name: Create Users
  hosts: all_servers
  become: yes  # This allows running commands as sudo or root
  vars_files:
    - var_users.yml
  tasks:
    - name: Create users
      user:
        name: "{{ item.username }}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password }}"
        state: present
      with_items: "{{ users }}"