---
- name: Download and Install Filebeat using Elastic repository
  hosts: ubuntu-servers
  gather_facts: yes
  become: yes  # Use sudo to install
  tasks:
    - name: Check if Filebeat is installed
      become: yes
      command: dpkg-query -W -f='${Status}' filebeat
      register: filebeat_status
      changed_when: false  # Treat the task as not changed, regardless of the result
      ignore_errors: true  # Ignore errors if the package is not installed

    - name: Display Filebeat status
      debug:
        msg: "{{ 'Filebeat is installed' if filebeat_status.stdout is search('install ok installed') else 'Filebeat is not installed' }}"

    - name: Import Elastic GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
      when: filebeat_status.failed  # Only run if Filebeat is not installed

    - name: Add Elastic APT repository for Filebeat
      apt_repository:
        repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
        state: present
        filename: 'elastic-beats'
        update_cache: yes
      when: filebeat_status.failed  # Only run if Filebeat is not installed

    - name: Update package cache
      apt:
        update_cache: yes
      when: filebeat_status.failed  # Only run if Filebeat is not installed

    - name: Install Filebeat 7.8.0
      apt:
        name: filebeat=7.8.0
        state: present
      when: filebeat_status.failed  # Only run if Filebeat is not installed

    - name: Ensure Filebeat service is enabled and running
      service:
        name: filebeat
        enabled: yes
        state: started
      when: filebeat_status.failed  # Only run if Filebeat is not installed